// Code generated by scripts/current-form-candidates.mjs; DO NOT EDIT.

package currentformregistry

var refs = map[string]Ref{
	"EdgeWorker":         ref("EdgeWorker", "sha256:226d21f90c739cd749fe41525d4fc3ddd848938aa270df1fdf10f273d8d4e0f8", "sha256:71bf6a9afb10559711fb3553f6c8f0f4d2ac470de37149df8d12e049920f1716"),
	"RelationalDatabase": ref("RelationalDatabase", "sha256:75e4f1fc7cd894df2ffaebc0655a48d9378150fe8700d3460ec2ecc70e6a26a7", "sha256:256b6cb3769fa1a4aaccf4a0e531458ca157869273f681b22f0a1e318a4cfa6f"),
	"ObjectBucket":       ref("ObjectBucket", "sha256:86ae3a9dfe78ff0c085dc5640adb36213a58cea1a7c18f43dae319835d554f3a", "sha256:9c362a4f38706e1d4e3086b24247bca0555643c71228c304db375702c33de6fe"),
	"KeyValueStore":      ref("KeyValueStore", "sha256:f0ccd47c4f6259b6d2f88503e0eacec2aee4a99f3b96164634ee761fe6f93923", "sha256:37e54706c0bf6c1298067ed36d8a36ba89e491eff074bacf9851abe59ea9b178"),
	"Queue":              ref("Queue", "sha256:b37964c96b7a0efba07cd30c2cd0f51a5ccfdf57e60de53eb5285d8a6c8d8211", "sha256:73fc1cc40cf1e3b81fb3fa2246c96e6170a462c7379261e00ce2ff3852cb9882"),
	"Schedule":           ref("Schedule", "sha256:4d99cf7dcc944a91f796c3b028bfd8a48337b0f91de2b1b84b75d647d171ffc3", "sha256:4b8a549406cc2b0c009fbc5ab3bfbbb94977c836e7cf3182a1ca8faabd443e53"),
	"ContainerService":   ref("ContainerService", "sha256:ecef25ff1d48e5a9d5d8f0368834477c8d85984b4b3b9bb874c5f0cddd28a8ca", "sha256:eae62434179ba2659a11c1099ddbe727356b9a6d66733b8bedbdc80b660f3bc4"),
	"StatefulEntity":     ref("StatefulEntity", "sha256:d620a11017105ab9caa26a5d61d7b87547e8ef0a71310c96441f22ab35c2930f", "sha256:576db2dc20a0f791ea027b2b5b07d64846a75d39929510f0f89fd4e0befa3ba2"),
	"VectorIndex":        ref("VectorIndex", "sha256:292df10a0aa0ccb6b8de6727d4772b0aaae282a73b51912d7da6bdccd9179183", "sha256:2ef7e04d40cc1b4dc96c336ba9e6fb4d45293dc7273532438cab43dac869cdd7"),
}
