// Code generated by scripts/current-form-candidates.mjs; DO NOT EDIT.

package currentformregistry

var refs = map[string]Ref{
	"EdgeWorker":         ref("EdgeWorker", "sha256:226d21f90c739cd749fe41525d4fc3ddd848938aa270df1fdf10f273d8d4e0f8", "sha256:b8f7c2cae932f9d6e25eb9dc3493862d5b9c0189ad92dfba63e8d24997b6e2a9"),
	"RelationalDatabase": ref("RelationalDatabase", "sha256:75e4f1fc7cd894df2ffaebc0655a48d9378150fe8700d3460ec2ecc70e6a26a7", "sha256:dfc78dba30edda0f948dbb74b7a2b11a7fa7e25b8f23ac8c19b8ede1cb954cf0"),
	"ObjectBucket":       ref("ObjectBucket", "sha256:86ae3a9dfe78ff0c085dc5640adb36213a58cea1a7c18f43dae319835d554f3a", "sha256:2976e6cf14d45a1e0b9bfc0cb3290b54008d6508e20f9d457d826d8ea5abaf9f"),
	"KeyValueStore":      ref("KeyValueStore", "sha256:f0ccd47c4f6259b6d2f88503e0eacec2aee4a99f3b96164634ee761fe6f93923", "sha256:d358488aaa48c739acd251c87b9f5fb3217481e468c524e46a4b53e82b0030f6"),
	"Queue":              ref("Queue", "sha256:b37964c96b7a0efba07cd30c2cd0f51a5ccfdf57e60de53eb5285d8a6c8d8211", "sha256:ed060f4a98da85d9dc3b44ac606ebfd95006a3feaee60e9f6e4ebb0e4c60d740"),
	"Schedule":           ref("Schedule", "sha256:4d99cf7dcc944a91f796c3b028bfd8a48337b0f91de2b1b84b75d647d171ffc3", "sha256:4d11c8740003449e9ba5bcab819d88596ad74edcd4ca8ae9a193c73389e21551"),
	"ContainerService":   ref("ContainerService", "sha256:ecef25ff1d48e5a9d5d8f0368834477c8d85984b4b3b9bb874c5f0cddd28a8ca", "sha256:aebbdaa7473be2d857c1f948521bf86ca6c30d84ca7e9279b84b49edc4fcc888"),
	"StatefulEntity":     ref("StatefulEntity", "sha256:d620a11017105ab9caa26a5d61d7b87547e8ef0a71310c96441f22ab35c2930f", "sha256:e09941a026da95c4eeb9535b5627530ea4c18e0caf3cd31be917f394ce4e54d6"),
	"VectorIndex":        ref("VectorIndex", "sha256:292df10a0aa0ccb6b8de6727d4772b0aaae282a73b51912d7da6bdccd9179183", "sha256:e0e92e8134ce323a3364d110fd454a647a1428e1c5112300956522f7d53a7070"),
}
