package provider

// v3_schema_evolution_test.go enforces the rule stated in
// v3_schema_evolution.go: when a moving Form line may keep its Terraform
// resource type, and when it must mint a new one.

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	frameworkresource "github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"

	model "github.com/tako0614/terraform-provider-takoform/internal/currentformmodel"
	"github.com/tako0614/terraform-provider-takoform/internal/edgeformcatalog"
)

// v3SurfaceBaselinePath is the committed floor the evolution rule is measured
// against. It is hand-committed, never regenerated by a gate: a baseline a gate
// rewrites is a baseline that agrees with every change.
const v3SurfaceBaselinePath = "testdata/v3-schema-baseline.json"

// v3AttributeSurface is what the framework exposes about one attribute and what
// the rule is decidable over. Validators are deliberately absent: the framework
// gives no comparable rendering of one, and "relaxing validation" is allowed
// anyway, so a baseline that tried to pin them would only forbid the permitted
// direction.
type v3AttributeSurface struct {
	Type      string `json:"type"`
	Required  bool   `json:"required"`
	Optional  bool   `json:"optional"`
	Computed  bool   `json:"computed"`
	Sensitive bool   `json:"sensitive,omitempty"`
}

type v3ResourceSurface struct {
	Version    int64                         `json:"version"`
	Attributes map[string]v3AttributeSurface `json:"attributes"`
}

func v3CurrentSurface(t *testing.T) map[string]v3ResourceSurface {
	t.Helper()
	ctx := context.Background()
	surface := map[string]v3ResourceSurface{}
	for _, form := range edgeformcatalog.Forms {
		resource := v3Provider3CurrentResourceHarness(t, form, "", nil, v3Codecs())
		var response frameworkresource.SchemaResponse
		resource.Schema(ctx, frameworkresource.SchemaRequest{}, &response)
		if response.Diagnostics.HasError() {
			t.Fatalf("%s schema: %v", form.Kind, response.Diagnostics)
		}
		attributes := map[string]v3AttributeSurface{}
		for name, attribute := range response.Schema.Attributes {
			attributes[name] = v3AttributeSurface{
				Type:      attribute.GetType().String(),
				Required:  attribute.IsRequired(),
				Optional:  attribute.IsOptional(),
				Computed:  attribute.IsComputed(),
				Sensitive: attribute.IsSensitive(),
			}
		}
		surface[resource.resourceTypeName()] = v3ResourceSurface{
			Version: response.Schema.Version, Attributes: attributes,
		}
	}
	return surface
}

// TestV3TerraformSchemaEvolutionRuleHoldsTheSurface is the mechanical half of
// the evolution rule.
//
// The committed baseline is a FLOOR, not a snapshot: an additive change needs
// no edit here and passes, and a breaking one fails naming the resource type
// that would have to be minted instead. What the test cannot decide — whether
// an attribute that kept its name, type, and flags kept its MEANING — is stated
// in v3_schema_evolution.go and carried by review.
func TestV3TerraformSchemaEvolutionRuleHoldsTheSurface(t *testing.T) {
	t.Parallel()
	current := v3CurrentSurface(t)
	if os.Getenv("TAKOFORM_WRITE_SCHEMA_BASELINE") == "1" {
		raw, err := json.MarshalIndent(current, "", "  ")
		if err != nil {
			t.Fatal(err)
		}
		if err := os.MkdirAll(filepath.Dir(v3SurfaceBaselinePath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(v3SurfaceBaselinePath, append(raw, '\n'), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Fatalf("rewrote %s; re-run without TAKOFORM_WRITE_SCHEMA_BASELINE", v3SurfaceBaselinePath)
	}
	raw, err := os.ReadFile(v3SurfaceBaselinePath)
	if err != nil {
		t.Fatalf("read the committed surface baseline: %v", err)
	}
	var baseline map[string]v3ResourceSurface
	if err := json.Unmarshal(raw, &baseline); err != nil {
		t.Fatalf("decode the committed surface baseline: %v", err)
	}
	if len(baseline) == 0 {
		t.Fatal("the committed surface baseline is empty")
	}
	for _, resourceType := range v3SortedSurfaceKeys(baseline) {
		before := baseline[resourceType]
		after, kept := current[resourceType]
		if !kept {
			if resourceType == "takoform_edge_object_bucket" {
				// ObjectBucket was withdrawn from the current versionless family
				// and Provider 3 registration. Provider 2.1.1 remains the immutable
				// historical implementation; this major line does not reinterpret
				// that type as a different Form.
				continue
			}
			t.Errorf(
				"%s no longer exists. Removing a Terraform resource type breaks every configuration that "+
					"names it; keep it serving the state written under its own codec and mint a new type for the "+
					"new contract.",
				resourceType,
			)
			continue
		}
		if after.Version < before.Version {
			t.Errorf("%s schema version went backwards, %d to %d", resourceType, before.Version, after.Version)
		}
		for _, name := range v3SortedAttributeKeys(before.Attributes) {
			was := before.Attributes[name]
			is, present := after.Attributes[name]
			if !present {
				t.Errorf(
					"%s.%s was removed. Removing an attribute requires a NEW Terraform resource type "+
						"(%s_v2, or a different Form kind); the existing type must keep serving it.",
					resourceType, name, resourceType,
				)
				continue
			}
			if is.Type != was.Type {
				t.Errorf(
					"%s.%s changed type from %s to %s. Retyping an attribute requires a NEW Terraform "+
						"resource type (%s_v2, or a different Form kind).",
					resourceType, name, was.Type, is.Type, resourceType,
				)
			}
			if is.Required && !was.Required {
				t.Errorf(
					"%s.%s became Required. Making an attribute required invalidates every existing "+
						"configuration that omits it, so it requires a NEW Terraform resource type (%s_v2).",
					resourceType, name, resourceType,
				)
			}
			if was.Computed && !is.Computed {
				t.Errorf(
					"%s.%s stopped being Computed. A value the provider no longer writes reads as null in "+
						"every expression that consumes it, so it requires a NEW Terraform resource type (%s_v2).",
					resourceType, name, resourceType,
				)
			}
			if was.Sensitive && !is.Sensitive {
				t.Errorf(
					"%s.%s stopped being Sensitive, which would start printing a value the provider "+
						"previously withheld.",
					resourceType, name,
				)
			}
		}
		for _, name := range v3SortedAttributeKeys(after.Attributes) {
			if _, existed := before.Attributes[name]; existed {
				continue
			}
			if after.Attributes[name].Required {
				t.Errorf(
					"%s.%s was added as Required, which invalidates every existing configuration. "+
						"An addition to an existing resource type must be Optional or Computed.",
					resourceType, name,
				)
			}
		}
	}
	for _, resourceType := range v3SortedSurfaceKeys(current) {
		if _, existed := baseline[resourceType]; !existed {
			t.Logf("%s is new to this build and is not yet in the baseline floor", resourceType)
		}
	}
}

func v3SortedSurfaceKeys(surface map[string]v3ResourceSurface) []string {
	out := make([]string, 0, len(surface))
	for key := range surface {
		out = append(out, key)
	}
	sort.Strings(out)
	return out
}

func v3SortedAttributeKeys(attributes map[string]v3AttributeSurface) []string {
	out := make([]string, 0, len(attributes))
	for key := range attributes {
		out = append(out, key)
	}
	sort.Strings(out)
	return out
}

// TestV3EverySchemaCarriesTheLaneVersionAndAnUpgrader proves the mechanism the
// rule depends on exists on every resource of the lane, not only where it is
// currently needed.
func TestV3EverySchemaCarriesTheLaneVersionAndAnUpgrader(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	for _, form := range edgeformcatalog.Forms {
		resource := v3Provider3CurrentResourceHarness(t, form, "", nil, v3Codecs())
		var response frameworkresource.SchemaResponse
		resource.Schema(ctx, frameworkresource.SchemaRequest{}, &response)
		if response.Schema.Version != v3SchemaVersion {
			t.Errorf("%s schema version = %d, want %d", form.Kind, response.Schema.Version, v3SchemaVersion)
		}
		upgraders := resource.UpgradeState(ctx)
		if len(upgraders) != int(v3SchemaVersion) {
			t.Errorf("%s registers %d state upgraders, want one per earlier version (%d)",
				form.Kind, len(upgraders), v3SchemaVersion)
		}
		for version := int64(0); version < v3SchemaVersion; version++ {
			upgrader, registered := upgraders[version]
			if !registered {
				t.Errorf("%s registers no upgrader from schema version %d", form.Kind, version)
				continue
			}
			if upgrader.PriorSchema == nil || upgrader.StateUpgrader == nil {
				t.Errorf("%s upgrader from version %d is incomplete", form.Kind, version)
			}
		}
	}
}

// TestV3StateUpgraderRoundTrip drives the registered upgrader over real state
// and proves it loses nothing.
func TestV3StateUpgraderRoundTrip(t *testing.T) {
	host := newV3FakeHost(t)
	host.assignedOutputs = v3EndpointOutputs()
	resource := v3TestFormResource(t, "WorkerEndpoint", newV3TestProviderData(t, host))
	ctx := context.Background()
	schemaResponse := v3SchemaOf(t, resource)

	plan := v3PlanWith(t, ctx, schemaResponse, map[string]attr.Value{
		"name":   types.StringValue("worker-endpoint"),
		"worker": types.StringValue("module-worker"),
	})
	createResponse := frameworkresource.CreateResponse{
		State: tfsdk.State{Schema: schemaResponse.Schema, Raw: v3EmptyRaw(t, ctx, schemaResponse)},
	}
	resource.Create(ctx, frameworkresource.CreateRequest{Plan: plan}, &createResponse)
	if createResponse.Diagnostics.HasError() {
		t.Fatalf("create: %v", createResponse.Diagnostics)
	}

	upgrader, registered := resource.UpgradeState(ctx)[0]
	if !registered {
		t.Fatal("no upgrader is registered from schema version 0")
	}
	priorSchema, ok := any(*upgrader.PriorSchema).(schema.Schema)
	if !ok {
		t.Fatal("the registered prior schema is not a resource schema")
	}
	if priorSchema.Version != 0 {
		t.Fatalf("prior schema version = %d, want 0", priorSchema.Version)
	}
	request := frameworkresource.UpgradeStateRequest{
		State: &tfsdk.State{Schema: priorSchema, Raw: createResponse.State.Raw},
	}
	response := frameworkresource.UpgradeStateResponse{
		State: tfsdk.State{Schema: schemaResponse.Schema, Raw: v3EmptyRaw(t, ctx, schemaResponse)},
	}
	upgrader.StateUpgrader(ctx, request, &response)
	if response.Diagnostics.HasError() {
		t.Fatalf("upgrade: %v", response.Diagnostics)
	}
	if !response.State.Raw.Equal(createResponse.State.Raw) {
		t.Fatal("the version 0 upgrade changed state; it is declared as a whole-value carry")
	}
	// And the upgraded value is still readable through the CURRENT schema, which
	// is the whole point of a round trip.
	for name, want := range map[string]string{
		"name":     "worker-endpoint",
		"worker":   "module-worker",
		"hostname": v3TestEndpointHostname,
		"url":      v3TestEndpointURL,
	} {
		if got := v3StateString(t, ctx, response.State, name).ValueString(); got != want {
			t.Errorf("upgraded state %s = %q, want %q", name, got, want)
		}
	}
	// A missing prior state is a fault, not a silent empty upgrade.
	empty := frameworkresource.UpgradeStateResponse{
		State: tfsdk.State{Schema: schemaResponse.Schema, Raw: v3EmptyRaw(t, ctx, schemaResponse)},
	}
	upgrader.StateUpgrader(ctx, frameworkresource.UpgradeStateRequest{}, &empty)
	if !empty.Diagnostics.HasError() {
		t.Fatal("an upgrade with no prior state was accepted")
	}
}

// v3PriorEndpointRef is the synthetic earlier definition version of
// WorkerEndpoint the Form-line tests record state under.
var v3PriorEndpointRef = v3FormRef{
	APIVersion:        edgeformcatalog.Family.APIVersion(),
	Kind:              "WorkerEndpoint",
	DefinitionVersion: "0.0.9",
	SchemaDigest:      "sha256:cccc111111111111111111111111111111111111111111111111111111111111",
	PackageDigest:     "sha256:cccc222222222222222222222222222222222222222222222222222222222222",
}

// TestV3FormLineAdvanceKeepsOneTerraformResourceType is the behavioural half of
// the rule: a Form line that advanced ADDITIVELY keeps one Terraform resource
// type, and that one type serves both identities for their whole lives.
//
// The prior definition version here declares the same outputs and one fewer
// desired field than the current one, which is exactly the additive shape the
// rule permits. Everything a resource can be asked to do is then driven against
// state recorded under the OLD identity — refresh, import, read the outputs it
// published, delete — while a NEW resource is created under the current one.
func TestV3FormLineAdvanceKeepsOneTerraformResourceType(t *testing.T) {
	host := newV3FakeHost(t)
	host.assignedOutputs = v3EndpointOutputs()
	ctx := context.Background()

	current, ok := edgeformcatalog.ByKind("WorkerEndpoint")
	if !ok {
		t.Fatal("WorkerEndpoint is not a declared family Form")
	}
	priorForm := current
	priorForm.DefinitionVersion = v3PriorEndpointRef.DefinitionVersion
	resource := v3ResourceWithSecondDefinitionVersion(
		t, "WorkerEndpoint", newV3TestProviderData(t, host), v3PriorEndpointRef, priorForm, false,
	)
	schemaResponse := v3SchemaOf(t, resource)
	if got := len(schemaResponse.Schema.Attributes); got == 0 {
		t.Fatal("the resource type serving two definition versions has no attributes")
	}

	// A NEW resource is created under the current default identity.
	plan := v3PlanWith(t, ctx, schemaResponse, map[string]attr.Value{
		"name":   types.StringValue("worker-endpoint"),
		"worker": types.StringValue("module-worker"),
	})
	createResponse := frameworkresource.CreateResponse{
		State: tfsdk.State{Schema: schemaResponse.Schema, Raw: v3EmptyRaw(t, ctx, schemaResponse)},
	}
	resource.Create(ctx, frameworkresource.CreateRequest{Plan: plan}, &createResponse)
	if createResponse.Diagnostics.HasError() {
		t.Fatalf("create under the current identity: %v", createResponse.Diagnostics)
	}
	if got := v3StateString(t, ctx, createResponse.State, "form_definition_version").ValueString(); got == v3PriorEndpointRef.DefinitionVersion {
		t.Fatal("a new resource was created under the PRIOR definition version")
	}

	// Existing state recorded under the OLD identity refreshes through the same
	// resource type, and publishes the outputs that definition declared.
	priorState := v3SeedStateRef(
		t, ctx, tfsdk.State{Schema: schemaResponse.Schema, Raw: createResponse.State.Raw}, v3PriorEndpointRef,
	)
	readResponse := frameworkresource.ReadResponse{State: priorState}
	resource.Read(ctx, frameworkresource.ReadRequest{State: priorState}, &readResponse)
	if readResponse.Diagnostics.HasError() {
		t.Fatalf("refresh of state recorded under the prior identity: %v", readResponse.Diagnostics)
	}
	if got := v3StateString(t, ctx, readResponse.State, "form_definition_version").ValueString(); got != v3PriorEndpointRef.DefinitionVersion {
		t.Fatalf("a refresh rebound the resource onto %q", got)
	}
	for name, want := range map[string]string{
		"hostname": v3TestEndpointHostname,
		"url":      v3TestEndpointURL,
	} {
		if got := v3StateString(t, ctx, readResponse.State, name).ValueString(); got != want {
			t.Errorf("prior-identity refresh output %s = %q, want the preserved %q", name, got, want)
		}
	}

	// The OLD exact FormRef imports through the same resource type.
	importID, err := json.Marshal(map[string]string{
		"space":             "prod",
		"apiVersion":        v3PriorEndpointRef.APIVersion,
		"kind":              v3PriorEndpointRef.Kind,
		"definitionVersion": v3PriorEndpointRef.DefinitionVersion,
		"schemaDigest":      v3PriorEndpointRef.SchemaDigest,
		"name":              "worker-endpoint",
	})
	if err != nil {
		t.Fatal(err)
	}
	importResponse := frameworkresource.ImportStateResponse{
		State: tfsdk.State{Schema: schemaResponse.Schema, Raw: v3EmptyRaw(t, ctx, schemaResponse)},
	}
	resource.ImportState(ctx, frameworkresource.ImportStateRequest{ID: string(importID)}, &importResponse)
	if importResponse.Diagnostics.HasError() {
		t.Fatalf("import of the prior exact FormRef: %v", importResponse.Diagnostics)
	}
	if got := v3StateString(t, ctx, importResponse.State, "form_definition_version").ValueString(); got != v3PriorEndpointRef.DefinitionVersion {
		t.Fatalf("import bound the resource to %q, want the named prior identity", got)
	}

	// And the OLD resource deletes under its own identity.
	before := len(host.resourceQueries)
	deleteResponse := frameworkresource.DeleteResponse{State: readResponse.State}
	resource.Delete(ctx, frameworkresource.DeleteRequest{State: readResponse.State}, &deleteResponse)
	if deleteResponse.Diagnostics.HasError() {
		t.Fatalf("delete under the prior identity: %v", deleteResponse.Diagnostics)
	}
	if len(host.resourceQueries) != before+1 {
		t.Fatalf("delete drove %d host queries, want one", len(host.resourceQueries)-before)
	}
	query := host.resourceQueries[len(host.resourceQueries)-1]
	if !strings.HasPrefix(query, "DELETE ") || !strings.Contains(query, v3PriorEndpointRef.SchemaDigest) {
		t.Fatalf("delete addressed %q, want the prior identity %q", query, v3PriorEndpointRef.SchemaDigest)
	}
}

// TestV3DerivedRevisionNamesAreDeterministicAndDistinct pins the two properties
// the derived name has to have to be usable as an identity.
func TestV3DerivedRevisionNamesAreDeterministicAndDistinct(t *testing.T) {
	t.Parallel()
	for _, form := range edgeformcatalog.Forms {
		resource := v3Provider3CurrentResourceHarness(t, form, "", nil, v3Codecs())
		if (form.Role == model.RoleRevision) != resource.derivesRevisionName() {
			t.Errorf("%s derives a revision name = %v, want it exactly for the revision role",
				form.Kind, resource.derivesRevisionName())
		}
	}
	bundleForm := mustForm(t, "WorkerBundle")
	versionForm := mustForm(t, "WorkerVersion")
	bundle := v3Provider3CurrentResourceHarness(t, bundleForm, "", nil, v3Codecs())
	version := v3Provider3CurrentResourceHarness(t, versionForm, "", nil, v3Codecs())
	digest := "sha256:" + strings.Repeat("ab", 32)
	first, ok := bundle.v3RevisionNameFromSpec(map[string]any{"manifestDigest": digest}, v3TestRevisionOwner)
	if !ok || !strings.HasPrefix(first, "bundle-") {
		t.Fatalf("bundle derived %q, want a bundle- name", first)
	}
	again, _ := bundle.v3RevisionNameFromSpec(map[string]any{"manifestDigest": digest}, v3TestRevisionOwner)
	if again != first {
		t.Fatalf("the same content derived %q then %q", first, again)
	}
	other, _ := bundle.v3RevisionNameFromSpec(map[string]any{
		"manifestDigest": "sha256:" + strings.Repeat("cd", 32),
	}, v3TestRevisionOwner)
	if other == first {
		t.Fatalf("different content derived the same name %q", first)
	}
	spec := map[string]any{
		"worker":   map[string]any{"apiVersion": edgeformcatalog.Family.APIVersion(), "kind": "ModuleWorker", "name": "counter"},
		"bundle":   map[string]any{"apiVersion": edgeformcatalog.Family.APIVersion(), "kind": "WorkerBundle", "name": first},
		"handlers": []string{"fetch"},
	}
	versionName, ok := version.v3RevisionNameFromSpec(spec, v3TestRevisionOwner)
	if !ok || !strings.HasPrefix(versionName, "version-") {
		t.Fatalf("version derived %q, want a version- name", versionName)
	}
	portable := regexp.MustCompile(model.PatternResourceName)
	for _, name := range []string{first, versionName} {
		if !portable.MatchString(name) {
			t.Fatalf("derived name %q is not a portable resource name", name)
		}
	}
	spec["handlers"] = []string{"fetch", "scheduled"}
	moved, _ := version.v3RevisionNameFromSpec(spec, v3TestRevisionOwner)
	if moved == versionName {
		t.Fatalf("a changed desired spec derived the same version name %q", versionName)
	}
	spec["handlers"] = []string{"fetch"}

	// A second owner of byte-identical content is a second owner. Both kinds
	// have to separate them: a Terraform address has exactly one owner, and a
	// content digest names the bytes rather than who declared them.
	peer := "counter-peer"
	peerBundle, ok := bundle.v3RevisionNameFromSpec(map[string]any{"manifestDigest": digest}, peer)
	if !ok || peerBundle == first {
		t.Fatalf("two owners derived one WorkerBundle name %q from identical content", first)
	}
	peerVersion, ok := version.v3RevisionNameFromSpec(spec, peer)
	if !ok || peerVersion == versionName {
		t.Fatalf("two owners derived one WorkerVersion name %q from an identical spec", versionName)
	}
	for _, name := range []string{peerBundle, peerVersion} {
		if !portable.MatchString(name) {
			t.Fatalf("derived name %q is not a portable resource name", name)
		}
	}
	// A derived name is still a function of the content: the owner is folded in
	// beside the content digest, never over it.
	if !strings.HasPrefix(peerBundle, "bundle-"+strings.TrimPrefix(digest, "sha256:")[:v3RevisionNameDigestLength]+"-") {
		t.Fatalf("the owner overwrote the content half of %q", peerBundle)
	}
	// No owner, no derived name. The provider refuses rather than minting one
	// two owners can both reach.
	if _, ok := bundle.v3RevisionNameFromSpec(map[string]any{"manifestDigest": digest}, ""); ok {
		t.Fatal("a revision name was derived without an owner")
	}
	// The longest owner the provider accepts still derives a portable name.
	longest, ok := bundle.v3RevisionNameFromSpec(
		map[string]any{"manifestDigest": digest}, strings.Repeat("z", model.ResourceNameMaxLength))
	if !ok || !portable.MatchString(longest) {
		t.Fatalf("the longest owner derived %q, which is not a portable resource name", longest)
	}
}

func mustForm(t *testing.T, kind string) model.Form {
	t.Helper()
	form, ok := edgeformcatalog.ByKind(kind)
	if !ok {
		t.Fatalf("%s is not a declared family Form", kind)
	}
	return form
}

// TestV3AttributeSurfaceRendersDeterministically guards the baseline's own
// comparability: a surface whose rendering is not stable would fail the floor
// test for reasons that have nothing to do with the rule.
func TestV3AttributeSurfaceRendersDeterministically(t *testing.T) {
	t.Parallel()
	first, err := json.Marshal(v3CurrentSurface(t))
	if err != nil {
		t.Fatal(err)
	}
	second, err := json.Marshal(v3CurrentSurface(t))
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(second) {
		t.Fatal("the derived Terraform surface is not deterministic")
	}
	if !strings.Contains(string(first), fmt.Sprintf("%q", "takoform_worker_version")) {
		t.Fatal("the derived surface does not carry the lane's resource types")
	}
}
